FROM golang:1.11 as build
WORKDIR /app
CMD git config --global url."ssh://git@git/".insteadOf "https://git.shpilevoy.ru/"
CMD go get -t
CMD GOOS=linux CGO_ENABLED=0 go build -o bin

FROM golang:alpine
RUN adduser --disabled-password --gecos "" app
COPY --from=build /app/bin /app/bin
USER app
WORKDIR /app
EXPOSE 8000
CMD /app/bin
